@extends('layouts.app')

@section('title', 'Admin Reports')

@section('content')
<div class="page-header">
    <div class="container-fluid px-4">
        <h1><i class="bi bi-file-earmark-text me-2"></i>Reports</h1>
        <p>Generate and manage system reports</p>
    </div>
</div>

<div class="row g-4 mb-4">
    <div class="col-12">
        <div class="card-modern">
            <div class="card-header">
                <i class="bi bi-plus-circle me-2"></i>Generate Report
            </div>
            <div class="card-body">
                <form action="{{ route('admin.reports.store') }}" method="POST">
                    @csrf
                    <div class="row g-3">
                        <div class="col-md-3">
                            <label for="type" class="form-label-modern">Report Type</label>
                            <select name="type" id="type" class="form-select form-control-modern" required>
                                <option value="platform_usage">Platform Usage</option>
                                <option value="transactions">Transactions</option>
                                <option value="feedback">Feedback</option>
                            </select>
                        </div>
                        <div class="col-md-3">
                            <label for="start_date" class="form-label-modern">Start Date</label>
                            <input type="date" name="start_date" id="start_date" class="form-control form-control-modern" required>
                        </div>
                        <div class="col-md-3">
                            <label for="end_date" class="form-label-modern">End Date</label>
                            <input type="date" name="end_date" id="end_date" class="form-control form-control-modern" required>
                        </div>
                        <div class="col-md-3 d-flex align-items-end">
                            <button type="submit" class="btn btn-primary-modern btn-modern w-100">
                                <i class="bi bi-download me-2"></i>Generate CSV
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row g-4">
    <div class="col-12">
        <div class="card-modern">
            <div class="card-header">
                <i class="bi bi-clock-history me-2"></i>Report History
            </div>
            <div class="card-body">
                @if($reports->isEmpty())
                    <p class="text-muted mb-0">No reports generated yet.</p>
                @else
                    <div class="table-responsive">
                        <table class="table table-modern">
                            <thead>
                                <tr>
                                    <th>Type</th>
                                    <th>Generated At</th>
                                    <th>Generated By</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($reports as $report)
                                <tr>
                                    <td>
                                        <span class="badge bg-primary badge-modern">
                                            {{ ucfirst(str_replace('_', ' ', $report->type)) }}
                                        </span>
                                    </td>
                                    <td>{{ $report->generated_at->format('M d, Y H:i') }}</td>
                                    <td>{{ $report->author->name ?? 'System' }}</td>
                                    <td>
                                        <div class="btn-group btn-group-sm">
                                            <a href="{{ route('admin.reports.download', $report) }}" class="btn btn-outline-primary">
                                                <i class="bi bi-download me-1"></i>Download
                                            </a>
                                            <form action="{{ route('admin.reports.destroy', $report) }}" method="POST" class="d-inline" onsubmit="return confirm('Are you sure you want to delete this report?');">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-outline-danger">
                                                    <i class="bi bi-trash me-1"></i>Delete
                                                </button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="mt-3">
                        {{ $reports->links() }}
                    </div>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection
